# Generated by Django 3.2.9 on 2021-11-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigationbuttons',
            options={'verbose_name': 'Кнопку', 'verbose_name_plural': 'Кнопки навигации'},
        ),
        migrations.AlterModelOptions(
            name='navigationdisplay',
            options={'verbose_name': 'Дисплей', 'verbose_name_plural': 'Дисплей'},
        ),
        migrations.AddField(
            model_name='navigationdisplay',
            name='deep',
            field=models.IntegerField(blank=True, null=True, verbose_name='глубина'),
        ),
        migrations.AlterField(
            model_name='navigationbuttons',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='текст кнопки'),
        ),
    ]
