# Generated by Django 3.2.9 on 2021-11-04 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20211104_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationdisplay',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.navigationdisplay', verbose_name='родительский дисплей'),
        ),
    ]
