# Generated by Django 3.2.9 on 2021-11-05 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_navigationdisplay_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationbuttons',
            name='action_click_url',
        ),
        migrations.AddField(
            model_name='navigationbuttons',
            name='action_click_display',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.navigationdisplay', verbose_name='ссылка на дисплей'),
        ),
    ]
