# Generated by Django 3.2.9 on 2021-11-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20211105_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=250, verbose_name='вопрос')),
                ('answer', models.TextField(verbose_name='ответ')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'вопросы',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='название сказки')),
                ('text', models.TextField(verbose_name='текст сказки')),
            ],
            options={
                'verbose_name': 'сказка',
                'verbose_name_plural': 'сказки',
            },
        ),
    ]
