# Generated by Django 3.2.9 on 2021-11-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_answers_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationdisplay',
            name='buttons',
            field=models.ManyToManyField(blank=True, null=True, to='main_app.NavigationButtons', verbose_name='набор кнопок'),
        ),
    ]
